### ISSUE TITLE
AC_INIT missing version argument in configure.sh

### ISSUE THREAD

**Issue by scimarin** [LibreDWG/libredwg#247]
...which leads to the failure of configure.sh. Adding the version number solves it (that corresponds to `autoconf --version`), as can be seen below.

```
AC_INIT([LibreDWG],
        [2.69],
        m4_esyscmd([build-aux/git-version-gen .tarball-version]),
        [libredwg@gnu.org],,
        [https://savannah.gnu.org/projects/libredwg/])
```
I don't think this is intended, and should be solved?

**Comment by rurban** [comment]
Nope. See https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Initializing-configure.html
`AC_INIT (package, version, [bug-report], [tarname], [url])`

Our version is generated by the git-version-gen script, which sometimes fails in the git step.
git is a bit unstable by design.
If it fails just do it again.
