### ISSUE TITLE
add gambas bindings

### ISSUE THREAD

**Issue by rurban** [LibreDWG/libredwg#269]
For https://github.com/tercoide/GauchoCAD
See the `work/gambas` branch, and the new add api, but in the end
only https://github.com/LibreDWG/gambas3-bindings

gambas3 has no pkgconfig support, and places its headers somewhere.

**Comment by rurban** [comment]
gambas support is done in libredwg. gambas provides no pkg-config, so we cannot get its headers. They are not in `/usr/include/gambas3` nor `/usr/share/gambas3/include`. So we cannot include it here, it must be under the gambas srcdir.
See  https://github.com/LibreDWG/gambas3-bindings

**Comment by belmotek** [comment]
Ok, I will see this whit the gambas development team in order to use it.

We (GauchoCAD) actually are using terminal tool dwgread > .json then 
decode json to made the objects collections then we write a output 
.json  file then convert .json to .dwg

Thank you very much for preparing the Gambas bindings.

Martín Belmonte

GauchoCAD team
