### ISSUE TITLE
Running precompiled version 0.12.4.4367

### ISSUE THREAD

**Issue by Nikhilsp** [LibreDWG/libredwg#398]
I am just trying to run an executable file on windows 10. Can  anyone tell me how to run the exe files in libredwg-0.12.4.4367-win64.zip. Do I need to install some other software to run the exe or download the source code too?

**Comment by Nikhilsp** [comment]
Any sugesstions? I tried running the exe files and I am not seeing any dialog box or anything. Just a cmd screen pops and closes.

**Comment by rurban** [comment]
You are probably missing the C runtime DLL's. Those are usually called MSVC Restributable.

It was compiled with the runtime for Microsoft Windows Server 2019, 10.0-17763 on Github actions.
Since I dont have a windows PC you have to find these DLL's by yourself. We are also not allowed to restribute it.

**Comment by Nikhilsp** [comment]
Thank you, I have installed all the versions of re-distributable from Microsoft. Still getting the same output.

**Comment by Nikhilsp** [comment]
works now
