### ISSUE TITLE
Text garbled, wrong M+5xxxx decoding with ANSI_936

### ISSUE THREAD

**Issue by FishOrBear** [LibreDWG/libredwg#428]
[fzw.zip](https://github.com/LibreDWG/libredwg/files/8401598/fzw.zip)
[fzw_pu.zip](https://github.com/LibreDWG/libredwg/files/8401627/fzw_pu.zip)

This file will not be garbled after ACAD PU.

**Comment by michal-josef-spacek** [comment]
DWG files in this issue:
* fzw.dwg - AC1015 (r2000)
* fzw_pu.dwg - AC1027 (r2013)

**Comment by rurban** [comment]
Both are ANSI_936 with lots of M+xxxx chars

**Comment by rurban** [comment]
Actually the logging of fzw.dwg uses the old CP936 encoding (simplified chinese) correctly, and also converts it to UTF-8 for DXF.
The r2013 format logs the strings as utf-8, because that's the internal codepage since r2007.

what is missing is understanding of such old dxf files with \M+5xxyy 936 encodings, and other asian MIF formats.
